export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_USER = "GET_USER"
export const GET_CATEGORY = "GET_CATEGORY"
export const TOGGLE_LOGIN = "TOGGLE_LOGIN"
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS"

export default {
  GET_PRODUCTS,
  GET_USER,
  GET_CATEGORY,
  TOGGLE_LOGIN,
  UPDATE_SEARCH_RESULTS,
}
