
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const LOG_IN = 'LOG_IN'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'
export const CREATE_USER = 'CREATE_USER'
export const MARKUS_SEARCH = 'MARKUS_SEARCH'
export const GET_CATEGORY = "GET_CATEGORY"
export const SEARCH_ITEMS = 'SEARCH_ITEMS'
export const LOG_OUT = 'LOG_OUT'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_CART = 'UPDATE_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const GET_ME = 'GET_ME'
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'


export default {
    GET_CATEGORY,
    GET_PRODUCTS, 
    LOG_IN, 
    TOGGLE_MODAL, 
    UPDATE_SEARCH_RESULTS,
    CREATE_USER,
    MARKUS_SEARCH, 
    SEARCH_ITEMS,
    LOG_OUT,
    UPDATE_USER_INFO,
    ADD_TO_CART, 
    UPDATE_CART,
    REMOVE_FROM_CART,
    EMPTY_CART,
    GET_ME,
    GET_ALL_ORDERS,
    CHANGE_STATUS,
    REMOVE_PRODUCT
}





