
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_USER = 'GET_USER'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'
export const CREATE_USER = 'CREATE_USER'
export const GET_CATEGORY = "GET_CATEGORY"

export default {
    GET_CATEGORY,
    GET_PRODUCTS, 
    GET_USER, 
    TOGGLE_MODAL, 
    UPDATE_SEARCH_RESULTS,
    CREATE_USER
}





