export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const SAVE_USER = 'SAVE_USER'
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'

export default {SAVE_PRODUCTS, SAVE_USER, UPDATE_SEARCH_RESULTS}