export const SAVE_PRODUCTS = "SAVE_PRODUCTS"
export const SAVE_USER = "SAVE_USER"
export const SAVE_CATEGORY = "SAVE_CATEGORY"
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS"
export const LOG_IN_TOGGLE = "LOG_IN_TOGGLE"

export default {
  SAVE_PRODUCTS,
  SAVE_USER,
  SAVE_CATEGORY,
  LOG_IN_TOGGLE,
  UPDATE_SEARCH_RESULTS,
}
