export const SAVE_PRODUCTS = "SAVE_PRODUCTS"
export const SET_ROLE = "SET_ROLE"
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS"
export const MODAL_TOGGLE = "LOG_IN_TOGGLE"
export const LOG_OUT = "LOG_OUT"
export const SAVE_PRODUCT_IN_CART = "SAVE_PRODUCT_IN_CART"
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const REMOVE_ALL_CART_ITEMS = "REMOVE_ALL_CART_ITEMS"
export const SAVE_ALL_ORDERS = "SAVE_ALL_ORDERS"
export const REMOVE_PRODUCT_FROM_STATE = "REMOVE_PRODUCT_FROM_STATE"
export const SAVE_USER = "SAVE_USER"
export const SAVE_ERROR = "SAVE_ERROR"
export const UPDATE_DELIVERY = "UPDATE_DELIVERY"
export const SET_ERROR = 'SET_ERROR'
export const UPDATE_ORDER = 'UPDATE_ORDER' 
export const CLEAR_ERROR = 'CLEAR_ERROR'

export default {
    SAVE_PRODUCTS, 
    SET_ROLE, 
    MODAL_TOGGLE, 
    UPDATE_SEARCH_RESULTS, 
    LOG_OUT,
    SAVE_PRODUCT_IN_CART,
    UPDATE_CART_ITEM,
    REMOVE_CART_ITEM,
    REMOVE_ALL_CART_ITEMS,
    SAVE_ALL_ORDERS,
    REMOVE_PRODUCT_FROM_STATE,
    SAVE_USER,
    SAVE_ERROR,
    UPDATE_DELIVERY,
    SET_ERROR,
    UPDATE_ORDER,
    CLEAR_ERROR
}
